GET http://localhost:3000/api/clients HTTP/1.1

GET http://localhost:3000/api/clients/id HTTP/1.1

POST http://localhost:3000/api/clients HTTP/1.1
Content-Type: application/json

{
  "dni":"491-230903-1000T",
  "fullName": "Saul Lagos",
  "email": "lagosmsaul@gmail.com",
  "phoneNumber": "+505 89082564",
  "address": "UNI-RUACS",
  "birthDate": "2023-09-23"
}


# Esto se puede cambiar de forma parcial pero lo correcto seria mandar todo el nuevo recurso
PUT http://localhost:3000/api/clients/id HTTP/1.1
Content-Type: application/json

{
  "fullName": "Dani-sama"
}

DELETE http://localhost:3000/api/clients/id HTTP/1.1

# Departments

GET http://localhost:3000/api/departments HTTP/1.1